import React from 'react'
import ReactDOMServer from 'react-dom/server'
import {
  MarginReport,
  MarginReportItem,
} from '../../domain/value-objects/MarginReport'
import dayjs from 'dayjs'
import {formatDate} from '../../../../common/utils/formatDate'

/*
Why do we use raw css when working with React?
It was 2x times faster for me to copy/paste the raw css for a prototype
then doing things right. Please, refactor.
 */
const css = `
   table {
      font-family: arial, sans-serif;
      font-size: x-small;
      border-collapse: collapse;
      width: 100%;
    }
    
    .error {
      color: red
    }

    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }

    tr:nth-child(even) {
      background-color: #dddddd;
    }
`

function MarginItemTable({
  title,
  data,
}: {
  title: string
  data: MarginReportItem[]
}) {
  if (!data || data.length === 0) {
    return null
  }

  return (
    <>
      <h3>{title}</h3>
      <table>
        <tr>
          <th>Bucket</th>
          <th>Vendor</th>
          <th>Item Number</th>
          <th>Description</th>

          <th>Retail Price Date</th>
          <th>Invoice Date</th>
          <th>Invoice Number</th>
          <th>Store</th>

          <th>Invoice Cost</th>
          <th>Retail Price</th>
          <th>Master Retail Price</th>
          <th>Custom Retail Price</th>
          <th>Gross Margin</th>

          <th>Margin Q1</th>
          <th>Margin Q2</th>
          <th>Margin Q3</th>
        </tr>
        {data.map((item) => (
          <tr key={item.VendorName + '_' + item.ItemNumber}>
            <td>{item.Bucket}</td>
            <td>{item.VendorName}</td>
            <td>{item.ItemNumber}</td>
            <td>{item.Description}</td>

            <td>{formatDate(item.RetailPriceDate)}</td>
            <td>{formatDate(item.InvoiceDate)}</td>
            <td>{item.InvoiceNumber}</td>
            <td>{item.StoreName}</td>

            <td>{item.InvoiceCost}</td>
            <td>{item.RetailPrice}</td>
            <td>{item.MasterRetailPrice}</td>
            <td>{item.CustomRetailPrice}</td>
            <td>{item.Margin}</td>

            <td>{item.MarginQ1}</td>
            <td>{item.MarginQ2}</td>
            <td>{item.MarginQ3}</td>
          </tr>
        ))}
      </table>
    </>
  )
}

export function marginReportToHTML({
  sourceName,
  reportStarted,
  reportEnded,
  error,
  resultsArePartial,
  items,
  since,
}: MarginReport): string {
  const executionTimeInMinutes = dayjs(reportEnded).diff(
    reportStarted,
    'minutes',
  )

  return ReactDOMServer.renderToString(
    <>
      <style>{css}</style>
      <h1>Margin Outliers Report ({formatDate(reportEnded)})</h1>
      <p>
        The report was build using historical data from {sourceName} since{' '}
        {formatDate(since)}. Took {executionTimeInMinutes} minutes to compute.
      </p>
      {error && (
        <>
          <hr />
          <h3 className="error">There was an Error!</h3>
          <p className="error">{error}</p>
          <hr />
        </>
      )}
      {items.length === 0 && (
        <>
          <h3>No outliers</h3>
          <p>We have not found any outliers.</p>
        </>
      )}
      <MarginItemTable
        title="Margin Compression"
        data={items.filter((x) => x.MarginStatus === 'Compression')}
      />
      <br />
      <MarginItemTable
        title="Margin Expansion"
        data={items.filter((x) => x.MarginStatus === 'Expansion')}
      />
      {resultsArePartial && (
        <>
          <h3>Results you see are partial</h3>
          <p>
            There are more margin outliers. We didnt include them into the
            report to save execution time.
          </p>
        </>
      )}
      <hr />
      <p>
        This report was generated by an automatic system. Please, contact
        engagingenterprisesltd@gmail.com for support.
      </p>
    </>,
  )
}
